version: '3.2'
services:
  db:
    image: 'postgres:13'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    command: [ "postgres", "-c", "log_statement=all" ]
