spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
  config:
    activate:
      on-profile: default

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
  config:
    activate:
      on-profile: dev

---

jwt:
  secret:
    access: CfDFNdA+QnpPRc+PQ0zadpyKfdHVzbbnLTtTblvR2Zn8avMFTrSgCSnrF5/T16jI4FsUsTkvMrB31Lj0ol0I+w==
    refresh: GkExH3TBFqh4p/qTSgs2dNlZXGkPuIfkVymRuBJcGxA36cesFlb5vjQJh/JGyLylfqdCzovO7gelnN2mtYpaiA==

mybatis:
  type-handlers-package: org.hse.parkings.handler

springdoc:
  swagger-ui:
    path: /swagger.html
    disable-swagger-default-url: true
  api-docs:
    path: /swagger

server:
  port: ${PORT:8080}
