auth:
  user:
    login: user
    password: user
  admin:
    login: admin
    password: admin

spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456

mybatis:
  type-handlers-package: org.hse.parkings.handler

springdoc:
  swagger-ui:
    path: /swagger.html
  api-docs:
    path: /swagger

server:
  port: ${PORT:8080}
