name: build + tests run
on:
  push:
    branches:
      - develop
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Tests coverage
        run: mvn clean surefire-report:report-only -Dformat=xml org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report

      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          check_name: 'Report'
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          include_passed: true
          fail_on_failure: true
          detailed_summary: true

      - name: Publish coverage report
        if: success()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{ github.workspace }}/target/site/jacoco/
