name: Parkings Tests
on:
  push:
    branches:
      - develop
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build + Tests
        run: mvn -B test surefire-report:report-only -Dformat=xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          check_name: 'Report'
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          include_passed: true
          fail_on_failure: true
          detailed_summary: true
